#!/usr/bin/env python3
"""
Generate HTML summary report with all SD visualizations
"""

import pandas as pd
import os
from pathlib import Path

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>SVbyEye SD Visualization Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #555;
            margin-top: 30px;
        }}
        .summary {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .summary table {{
            width: 100%;
            border-collapse: collapse;
        }}
        .summary th {{
            text-align: left;
            padding: 8px;
            background-color: #4CAF50;
            color: white;
        }}
        .summary td {{
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }}
        .sd-item {{
            background: white;
            padding: 20px;
            margin-bottom: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .sd-item h3 {{
            margin-top: 0;
            color: #4CAF50;
        }}
        .sd-item img {{
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 4px;
            margin-top: 10px;
        }}
        .sd-info {{
            display: grid;
            grid-template-columns: auto 1fr;
            gap: 10px;
            margin-bottom: 15px;
            font-size: 14px;
        }}
        .sd-info .label {{
            font-weight: bold;
            color: #666;
        }}
        .sd-info .value {{
            color: #333;
        }}
        .tag {{
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 12px;
            margin-right: 5px;
        }}
        .tag.gene {{
            background-color: #e3f2fd;
            color: #1976d2;
        }}
        .tag.t2t {{
            background-color: #f3e5f5;
            color: #7b1fa2;
        }}
        footer {{
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <h1>SVbyEye Segmental Duplication Visualization Report</h1>

    <div class="summary">
        <h2>Summary</h2>
        <p><strong>Total SD pairs visualized:</strong> {total_sds}</p>
        <p><strong>SDs with genes:</strong> {sds_with_genes}</p>
        <p><strong>SDs with T2T liftover:</strong> {sds_with_t2t}</p>
    </div>

    <div class="summary">
        <h2>SD Details</h2>
        <table>
            <tr>
                <th>SD ID</th>
                <th>Sample</th>
                <th>Haplotype</th>
                <th>Size (avg)</th>
                <th>Genes</th>
                <th>T2T Liftover</th>
            </tr>
            {summary_table_rows}
        </table>
    </div>

    <h2>Visualizations</h2>
    {sd_visualizations}

    <footer>
        Generated by SVbyEye Pipeline<br>
        <a href="https://github.com/daewoooo/SVbyEye">SVbyEye Documentation</a>
    </footer>
</body>
</html>
"""

def format_size(size):
    """Format size in bp to human readable"""
    if size >= 1000000:
        return f"{size/1000000:.2f} Mb"
    elif size >= 1000:
        return f"{size/1000:.2f} kb"
    else:
        return f"{size:.0f} bp"

def main(snakemake):
    """Generate HTML report"""

    # Load filtered SDs
    df = pd.read_csv(snakemake.input.filtered_sds, sep="\t")

    output_dir = snakemake.params.output_dir
    plots_dir = os.path.join(output_dir, "plots")

    print(f"Generating report for {len(df)} SDs...")

    # Calculate summary stats
    total_sds = len(df)
    sds_with_genes = 0
    sds_with_t2t = 0

    if 'SD1_has_exon' in df.columns and 'SD2_has_exon' in df.columns:
        sds_with_genes = ((df['SD1_has_exon'] == True) | (df['SD2_has_exon'] == True)).sum()

    if 'SD1_T2T' in df.columns and 'SD2_T2T' in df.columns:
        sds_with_t2t = ((df['SD1_T2T'].notna()) & (df['SD2_T2T'].notna())).sum()

    # Generate summary table rows
    summary_rows = []
    for idx, row in df.iterrows():
        sd_id = row['SD_ID']
        sample = row['Sample']
        haplotype = row['Haplotype']
        avg_size = row.get('avg_size', 0)

        # Gene info
        genes = row.get('Gene_names', 'None')
        if pd.isna(genes) or genes == 'None':
            genes = '-'

        # T2T liftover
        has_t2t = 'No'
        if 'SD1_T2T' in row and pd.notna(row['SD1_T2T']) and row['SD1_T2T'] != 'None':
            has_t2t = 'Yes'

        summary_rows.append(f"""
            <tr>
                <td><a href="#{sd_id}">{sd_id}</a></td>
                <td>{sample}</td>
                <td>{haplotype}</td>
                <td>{format_size(avg_size)}</td>
                <td>{genes}</td>
                <td>{has_t2t}</td>
            </tr>
        """)

    summary_table_rows = "\n".join(summary_rows)

    # Generate visualization sections
    viz_sections = []
    for idx, row in df.iterrows():
        sd_id = row['SD_ID']
        sample = row['Sample']
        haplotype = row['Haplotype']

        # Check if plot exists
        plot_file = os.path.join(plots_dir, f"{sd_id}.png")
        if not os.path.exists(plot_file):
            print(f"  Warning: Plot not found for {sd_id}")
            continue

        # Relative path for HTML
        plot_rel_path = f"plots/{sd_id}.png"

        # Build tags
        tags = []
        if 'SD1_has_exon' in row and (row['SD1_has_exon'] == True or row.get('SD2_has_exon') == True):
            genes = row.get('Gene_names', 'None')
            if genes != 'None' and not pd.isna(genes):
                tags.append(f'<span class="tag gene">Genes: {genes}</span>')
        if 'SD1_T2T' in row and pd.notna(row['SD1_T2T']) and row['SD1_T2T'] != 'None':
            tags.append('<span class="tag t2t">T2T Liftover</span>')

        tags_html = " ".join(tags)

        # Build info grid
        info_items = []
        info_items.append(('<span class="label">Sample:</span>', f'<span class="value">{sample}</span>'))
        info_items.append(('<span class="label">Haplotype:</span>', f'<span class="value">{haplotype}</span>'))
        info_items.append(('<span class="label">SD1:</span>', f'<span class="value">{row["SD1_original"]}</span>'))
        info_items.append(('<span class="label">SD2:</span>', f'<span class="value">{row["SD2_original"]}</span>'))

        if 'SD1_T2T' in row and pd.notna(row['SD1_T2T']) and row['SD1_T2T'] != 'None':
            info_items.append(('<span class="label">SD1 (T2T):</span>', f'<span class="value">{row["SD1_T2T"]}</span>'))
            info_items.append(('<span class="label">SD2 (T2T):</span>', f'<span class="value">{row["SD2_T2T"]}</span>'))

        avg_size = row.get('avg_size', 0)
        info_items.append(('<span class="label">Avg Size:</span>', f'<span class="value">{format_size(avg_size)}</span>'))

        info_grid = "\n".join([f"{label} {value}" for label, value in info_items])

        viz_sections.append(f"""
        <div class="sd-item" id="{sd_id}">
            <h3>{sd_id} {tags_html}</h3>
            <div class="sd-info">
                {info_grid}
            </div>
            <img src="{plot_rel_path}" alt="{sd_id} visualization">
        </div>
        """)

    sd_visualizations = "\n".join(viz_sections)

    # Generate HTML
    html = HTML_TEMPLATE.format(
        total_sds=total_sds,
        sds_with_genes=sds_with_genes,
        sds_with_t2t=sds_with_t2t,
        summary_table_rows=summary_table_rows,
        sd_visualizations=sd_visualizations
    )

    # Write report
    with open(snakemake.output.report, 'w') as f:
        f.write(html)

    print(f"Report saved to: {snakemake.output.report}")

if __name__ == "__main__":
    main(snakemake)
