#!/usr/bin/env python3
"""Assemble an HTML report describing the SVbyEye visualisation outputs."""

from __future__ import annotations

from pathlib import Path
from typing import List

import pandas as pd

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>SVbyEye SD Visualisation Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #555;
            margin-top: 30px;
        }}
        .summary {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .summary table {{
            width: 100%;
            border-collapse: collapse;
        }}
        .summary th {{
            text-align: left;
            padding: 8px;
            background-color: #4CAF50;
            color: white;
        }}
        .summary td {{
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }}
        .sd-item {{
            background: white;
            padding: 20px;
            margin-bottom: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .sd-item h3 {{
            margin-top: 0;
            color: #4CAF50;
        }}
        .sd-item img {{
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 4px;
            margin-top: 10px;
        }}
        .sd-info {{
            display: grid;
            grid-template-columns: auto 1fr;
            gap: 10px;
            margin-bottom: 15px;
            font-size: 14px;
        }}
        .sd-info .label {{
            font-weight: bold;
            color: #666;
        }}
        .sd-info .value {{
            color: #333;
        }}
        .tag {{
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 12px;
            margin-right: 5px;
        }}
        .tag.gene {{
            background-color: #e3f2fd;
            color: #1976d2;
        }}
        .tag.t2t {{
            background-color: #f3e5f5;
            color: #7b1fa2;
        }}
        footer {{
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #666;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <h1>SVbyEye Segmental Duplication Visualisation Report</h1>

    <div class="summary">
        <h2>Summary</h2>
        <p><strong>Total SD pairs visualised:</strong> {total_sds}</p>
        <p><strong>SDs with annotated genes:</strong> {sds_with_genes}</p>
        <p><strong>SDs with T2T liftover:</strong> {sds_with_t2t}</p>
    </div>

    <div class="summary">
        <h2>SD Details</h2>
        <table>
            <tr>
                <th>SD ID</th>
                <th>Sample</th>
                <th>Haplotype</th>
                <th>Size (avg)</th>
                <th>Genes</th>
                <th>T2T Liftover</th>
            </tr>
            {summary_table_rows}
        </table>
    </div>

    <h2>Visualisations</h2>
    {sd_visualisations}

    <footer>
        Generated by the SVbyEye pipeline<br>
        <a href="https://github.com/daewoooo/SVbyEye">SVbyEye documentation</a>
    </footer>
</body>
</html>
"""


def format_size(size: float) -> str:
    """Convert a size in base pairs into a human-readable string."""

    if size >= 1_000_000:
        return f"{size / 1_000_000:.2f} Mb"
    if size >= 1_000:
        return f"{size / 1_000:.2f} kb"
    return f"{size:.0f} bp"


def _gene_description(row: pd.Series) -> str:
    genes = row.get("Gene_names", "-")
    if pd.isna(genes) or genes == "None":
        return "-"
    return str(genes)


def _has_t2t(row: pd.Series) -> bool:
    sd1 = row.get("SD1_T2T")
    sd2 = row.get("SD2_T2T")
    return pd.notna(sd1) and pd.notna(sd2) and sd1 != "None" and sd2 != "None"


def _summary_rows(df: pd.DataFrame) -> str:
    rows: List[str] = []
    for _, row in df.iterrows():
        sd_id = row["SD_ID"]
        rows.append(
            """
            <tr>
                <td><a href="#{sd_id}">{sd_id}</a></td>
                <td>{sample}</td>
                <td>{haplotype}</td>
                <td>{avg_size}</td>
                <td>{genes}</td>
                <td>{t2t}</td>
            </tr>
            """.format(
                sd_id=sd_id,
                sample=row["Sample"],
                haplotype=row["Haplotype"],
                avg_size=format_size(row.get("avg_size", 0)),
                genes=_gene_description(row),
                t2t="Yes" if _has_t2t(row) else "No",
            )
        )
    return "\n".join(rows)


def _tags(row: pd.Series) -> str:
    tags: List[str] = []
    sd1_has_exon = bool(row.get("SD1_has_exon", False))
    sd2_has_exon = bool(row.get("SD2_has_exon", False))
    if sd1_has_exon or sd2_has_exon:
        genes = _gene_description(row)
        if genes != "-":
            tags.append(f'<span class="tag gene">Genes: {genes}</span>')
    if _has_t2t(row):
        tags.append('<span class="tag t2t">T2T Liftover</span>')
    return " ".join(tags)


def _info_grid(row: pd.Series) -> str:
    items = [
        ("Sample", row["Sample"]),
        ("Haplotype", row["Haplotype"]),
        ("SD1", row["SD1_original"]),
        ("SD2", row["SD2_original"]),
    ]

    if _has_t2t(row):
        items.extend(
            [
                ("SD1 (T2T)", row["SD1_T2T"]),
                ("SD2 (T2T)", row["SD2_T2T"]),
            ]
        )

    items.append(("Avg Size", format_size(row.get("avg_size", 0))))

    return "\n".join(
        f'<span class="label">{label}:</span> <span class="value">{value}</span>' for label, value in items
    )


def _visualisation_sections(df: pd.DataFrame, plots_dir: Path) -> str:
    sections: List[str] = []
    for _, row in df.iterrows():
        sd_id = row["SD_ID"]
        plot_path = plots_dir / f"{sd_id}.png"
        if not plot_path.exists():
            print(f"  WARNING: plot not found for {sd_id} ({plot_path})")
            continue

        sections.append(
            """
        <div class="sd-item" id="{sd_id}">
            <h3>{sd_id} {tags}</h3>
            <div class="sd-info">
                {info_grid}
            </div>
            <img src="plots/{sd_id}.png" alt="{sd_id} visualisation" />
        </div>
            """.format(sd_id=sd_id, tags=_tags(row), info_grid=_info_grid(row))
        )
    return "\n".join(sections)


def main(snakemake) -> None:  # type: ignore[annotation-unchecked]
    """Render the HTML report summarising SVbyEye outputs."""

    df = pd.read_csv(snakemake.input.filtered_sds, sep="\t")
    output_dir = Path(snakemake.params.output_dir)
    plots_dir = output_dir / "plots"

    print(f"Generating HTML report for {len(df)} SD pairs")

    total_sds = len(df)
    sds_with_genes = 0
    if {"SD1_has_exon", "SD2_has_exon"} <= set(df.columns):
        sds_with_genes = ((df["SD1_has_exon"] == True) | (df["SD2_has_exon"] == True)).sum()  # noqa: E712

    sds_with_t2t = 0
    if {"SD1_T2T", "SD2_T2T"} <= set(df.columns):
        sds_with_t2t = (
            df["SD1_T2T"].notna()
            & df["SD2_T2T"].notna()
            & (df["SD1_T2T"] != "None")
            & (df["SD2_T2T"] != "None")
        ).sum()

    summary_rows = _summary_rows(df)
    visualisations = _visualisation_sections(df, plots_dir)

    html = HTML_TEMPLATE.format(
        total_sds=total_sds,
        sds_with_genes=sds_with_genes,
        sds_with_t2t=sds_with_t2t,
        summary_table_rows=summary_rows,
        sd_visualisations=visualisations,
    )

    with open(snakemake.output.report, "w", encoding="utf-8") as handle:
        handle.write(html)

    print(f"Report written to: {snakemake.output.report}")


if __name__ == "__main__":
    main(snakemake)
